animesite/anime/urls.py
from django.urls import path
from . import views

app_name = 'anime'

urlpatterns = [
    path('', views.index, name='index'),
    path('anime/', views.AnimeListView.as_view(), name='anime_list'),
    path('anime/<int:pk>/', views.AnimeDetailView.as_view(), name='anime_info'),
    path('anime/create/', views.AnimeCreateView.as_view(), name='create_anime'),
    path('anime/<int:pk>/update/', views.AnimeUpdateView.as_view(), name='update_anime'),
    path('director/<int:pk>/', views.DirectorDetailView.as_view(), name='director_info'),
    path('director/create/', views.DirectorCreateView.as_view(), name='create_director'),
    path('director/<int:pk>/update/', views.DirectorUpdateView.as_view(), name='update_director'),
    path('anime/<int:anime_id>/add_to_my_list/<int:user_id>/', views.AddToMyList, name='add_to_my_list'),
    path('anime/<int:anime_id>/delete_from_my_list/<int:user_id>/', views.DeleteFromMyList, name='delete_from_my_list'),
    path('anime/mylist', views.mylist, name='mylist'),
    path('studio/<int:pk>/', views.StudioDetailView.as_view(), name='studio_info'),
    path('studio/create/', views.StudioCreateView.as_view(), name='create_studio'),
    path('studio/<int:pk>/update/', views.StudioUpdateView.as_view(), name='update_studio'),
    path('anime/all', views.AnimeAllListView.as_view(), name='all_anime'),
]

animesite/animesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('users.urls')),
]

animesite/users/urls.py
from .views import SignUpView, UsersListView
from django.urls import path, include

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('users/', UsersListView.as_view(), name='users_list'),
]

animesite/anime/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Studio(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Director(models.Model):
    name = models.CharField(max_length=100)
    birth_date = models.DateTimeField('birth_date')
    image = models.FileField(upload_to="", blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('anime:director_info', args=[self.id])

class Anime(models.Model):
    title = models.CharField(max_length=100)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    studio = models.ForeignKey(Studio, on_delete=models.CASCADE)
    release_date = models.DateTimeField('release_date')
    image = models.FileField(upload_to="", blank=True, null=True)
    viewers = models.ManyToManyField(User, null=True, blank=True)
    description = models.CharField(max_length=3000, blank=True, null=True)
    link = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('anime:anime_info', args=[self.id])

# Create your models here.

animesite/users/models.py
from django.db import models

# Create your models here.

animesite/anime/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.contrib.auth.models import User, Permission
from django.contrib import messages

from .models import Anime, Director, Studio
from django.template import loader

def index(request) :
    return render(request, 'home.html')

class StudioDetailView(DetailView):
    model = Studio
    template_name = 'anime/studio_detail.html'

class StudioUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'anime.change_studio'
    model = Studio
    fields = ['name']

class StudioCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'anime.add_studio'
    model = Studio
    fields = ['name']

class DirectorDetailView(DetailView):
    model = Director
    template_name = 'anime/director_detail.html'

class DirectorCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'anime.add_director'
    model = Director
    fields = ['name', 'birth_date', 'image']

class DirectorUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'anime.change_director'
    model = Director
    fields = ['name', 'birth_date', 'image']

class AnimeDetailView(DetailView):
    model = Anime
    template_name = 'anime/anime_detail.html'

class AnimeCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'anime.add_anime'
    model = Anime
    fields = ['title', 'director', 'studio', 'release_date', 'image', 'description', 'link']

class AnimeUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'anime.change_anime'
    model = Anime
    fields = ['title', 'director', 'studio', 'release_date', 'image', 'description', 'link']

class AnimeListView(ListView):
    model = Anime
    template_name = 'anime/index.html'
    paginate_by = 5

    def get_ordering(self):
        return 'title'

class AnimeAllListView(ListView):
    model = Anime
    template_name = 'anime/anime_all.html'

    def get_ordering(self):
        return 'title'

def AddToMyList(request, anime_id, user_id):
    user = User.objects.get(id=user_id)
    anime = Anime.objects.get(id=anime_id)
    anime.viewers.add(user)
    anime.save()
    return render(request, 'anime/add_to_my_list.html', {'anime' : anime})

def DeleteFromMyList(request, anime_id, user_id):
    user = User.objects.get(id=user_id)
    anime = Anime.objects.get(id=anime_id)
    anime.viewers.remove(user)
    return render(request, 'anime/delete_from_my_list.html', {'anime' : anime})

def mylist(request):
    return render(request, 'anime/mylist.html')


# Create your views here.

animesite/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

class UsersListView(ListView):
    model = User
    template_name = 'users/index.html'

# Create your views here.

animesite/templates/anime/add_to_my_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2">
        <big>Аниме "{{ anime }}" успешно добавлено в ваш список.</big>
        <p><a class="btn btn-primary" href="{% url 'anime:anime_info' anime.pk %}">Вернуться</a></p>
    </div>
{% endblock %}

animesite/templates/anime/anime_all.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3>Все аниме</h3>
    <ul>
        {% for anime in object_list %}
            <big><li><a class="text-decoration-none" href="{% url 'anime:anime_info' anime.id %}">{{ anime.title }}</a></li></big>
        {% endfor %}
    </ul>
    {% if perms.anime.add_anime %}
        <a class="btn btn-danger" href="{% url 'anime:create_anime' %}">Добавить аниме</a>
    {% endif %}
    {% if perms.anime.add_director %}
        <a class="btn btn-danger" href="{% url 'anime:create_director' %}">Добавить режиссёра</a>
    {% endif %}
    {% if perms.anime.add_studio %}
        <a class="btn btn-danger" href="{% url 'anime:create_studio' %}">Добавить студию</a>
    {% endif %}
{% endblock %}

animesite/templates/anime/anime_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-sm-4">
            <div class="container p-4">
                <img src="{% static anime.image %}", width="300px">
                <div class="container p-2">
                    {% if user.is_authenticated %}
                        {% if anime in user.anime_set.all %}
                           <p><a class="btn btn-primary" href="{% url 'anime:delete_from_my_list' anime.id user.id %}">Убрать из списка просмотренных</a></p>
                        {% else %}
                          <p><a class="btn btn-primary" href="{% url 'anime:add_to_my_list' anime.id user.id %}">Добавить в список просмотренных</a></p>
                        {% endif %}
                    {% else %}
                        <p><a href="{% url 'login' %}">Войдите, чтобы добавить в свой список просмотренных</a></p>
                    {% endif %}
                    {% if perms.anime.change_anime %}
                        <div class="container p-2">
                            <p><a class="btn btn-danger" href="{% url 'anime:update_anime' anime.pk %}">Изменить данные</a></p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="container p-3">
            <h1>{{anime.title}}</h1>
                <div class="card p-2" style="width: 23rem">
                    <p><big>Студия: <a href="{% url 'anime:studio_info' anime.studio.pk %}">{{anime.studio}}</a></big></p>
                    <p><big>Режиссёр: <a href="{% url 'anime:director_info' anime.director.pk %}">{{ anime.director }}</a></big></p>
                    <p><big>Дата релиза: {{anime.release_date.date}}</big></p>
                    <p>В списке просмотренных у {{ anime.viewers.count }} пользователей</p>
                </div>
            <p>{{anime.description}}</p>
                <div class="card">
                    <h5 class="card-header">Трейлер</h5>
                    <div class="card-body">
                        <iframe width="640" height="360" src="{{ anime.link }}"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

animesite/templates/anime/anime_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>

animesite/templates/anime/delete_from_my_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-2">
        <big>Аниме "{{ anime }}" успешно удалено из вашего списка.</big>
        <p><a class="btn btn-primary" href="{% url 'anime:anime_info' anime.pk %}">Вернуться</a></p>
    </div>
{% endblock %}

animesite/templates/anime/director_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <h2>{{ director.name }}</h2>
        <p>Дата рождения: {{ director.birth_date.date }}</p>
        <div class="col-sm-4">
            <img src="{% static director.image %}", width="300px">
        </div>
        <div class="col-sm-7">
            <div class="card">
                <h4 class="card-header">Участие в проектах:</h4>
                <div class="card-body">
                {% for anime in director.anime_set.all %}
                    <h5><li><a href="{% url 'anime:anime_info' anime.id %}">{{ anime.title }}</a></li></h5>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% if perms.anime.change_director %}
        <div class="container p-2">
            <p><a class="btn btn-danger" href="{% url 'anime:update_director' director.pk %}">Изменить данные</a></p>
        </div>
    {% endif %}
{% endblock %}

animesite/templates/anime/director_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-3">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить">
        </form>
    </div>
{% endblock %}

animesite/templates/anime/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if object_list %}
        <ul>
            {% for anime in object_list %}
                <h3><li><a class="text-decoration-none" href="{% url 'anime:anime_info' anime.id %}">{{ anime.title }}</a></li></h3>
                <div class="row">
                    <div class="col-sm-3">
                        <img src="{% static anime.image %}" , width="250px">
                    </div>
                    <div class="col-sm-9">
                        <div class="card p-3">
                            <p>{{anime.description}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <p>Пусто.</p>
    {% endif %}
{% endblock %}

animesite/templates/anime/mylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container p-3">
        {% if user.is_authenticated %}
            <h3>Список просмотренных</h3>
            <h6>У вас в списке {{ user.anime_set.count }} аниме</h6>
            <ol>
                {% for anime in user.anime_set.all %}
                    <big><li>
                        <a class='text-decoration-none' href="{% url 'anime:anime_info' anime.pk %}">{{ anime }}</a>
                    </li></big>
                {% endfor %}
            </ol>
        {% else %}
        <big><a href="{% url 'login' %}">Авторизируйтесь, чтобы посмотреть свой список просмотренных</a></big>
        {% endif %}
    </div>
{% endblock %}

animesite/templates/anime/studio_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h3 >Аниме студии {{ studio }}</h3>
        {% for anime in studio.anime_set.all %}
            <big><li><a href="{% url 'anime:anime_info' anime.id %}">{{ anime.title }}</a></li></big>
        {% endfor %}
    </div>
    {% if perms.anime.change_studio %}
        <div class="container p-2">
            <p><a class="btn btn-danger" href="{% url 'anime:update_studio' studio.pk %}">Изменить данные</a></p>
        </div>
    {% endif %}
{% endblock %}

animesite/templates/anime/studio_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-3">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить">
        </form>
    </div>
{% endblock %}

animesite/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Animesite</title>
</head>
    <body>
        <div class="container">
            <header>
                {% include 'includes/header.html' %}
            </header>
            <main>
                {% block content %}
                    Тут мог бы быть контент...
                {% endblock %}
            </main>
            <footer>
                {% include 'includes/footer.html' %}
            </footer>
        </div>
    </body>
</html>

animesite/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-3">
        <h2>Добро пожаловать!</h2>
    </div>
{% endblock %}

animesite/templates/includes/footer.html
<div class="card bg-secondary p-1">
    <p class="card-text text-light">
        Разработка: Емельянов Алексей, 2022 г.
    </p>
</div>

animesite/templates/includes/header.html
<div class="card bg-info p-2">
    <div class="row">
        <div class="col-sm-3">
            <h1><a class="link-dark text-decoration-none" href="{% url 'anime:anime_list' %}" >Animesite</a></h1>
        </div>
        <div class="col-sm-2">
            <h5><a class="link-dark text-decoration-none" href="{% url 'anime:all_anime' %}">Все аниме</a></h5>
        </div>
        <div class="col-sm-2">
            <h5><a class="link-dark text-decoration-none" href="{% url 'anime:mylist' %}">Мой список</a></h5>
        </div>
        <div class="col-sm-2">
            <h5><a class="link-dark text-decoration-none" href="{% url 'users:users_list' %}">Список пользователей</a></h5>
        </div>
        <div class="col-sm-3">
            {% if user.is_authenticated %}
                <h5 class="card-title">Hi, {{user.username }}</h5>
                <a href="{% url 'logout' %}" class="link-dark">Log Out</a>
            {% else %}
                <p class="card-title">You are not logged in.</p>
                <a href="{% url 'login' %}" class="link-dark">Log In</a>
            {% endif %}
        </div>
    </div>
</div>

animesite/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-3">
        <h3>Список всех пользователей:</h3>
        {% for user in object_list %}
            <p><li>{{ user }}</li></p>
        {% empty %}
            Пусто.
        {% endfor %}
    </div>
{% endblock %}

animesite/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="container p-3">
        <h2>Регистрация нового пользователя</h2>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock %}